 services:
   db:
     image: postgres:15
#     environment:
#       - POSTGRES_PASSWORD=123456

   web:
     build: .
#     command: python manage.py runserver 0.0.0.0:8000
     command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
     volumes:
       - .:/project
       ports:
         - 8000:8000
       depends_on:
         - db
 db:
   image: postgres
   environment:
     POSTGRES_PASSWORD: 123456

   volumes:
     - postgres_data:/var/lib/postgresql/data/
 volumes:
   postgres_data:
#docker build --tag postgres .
# docker run --name some-postgres -e POSTGRES_PASSWORD=123456 -d postgres