# Generated by Django 3.2.9 on 2022-08-22 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата присоеденения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'created'), ('2', 'in_progress'), ('3', 'completed')], default='1', max_length=2),
        ),
    ]
