# Generated by Django 3.2.9 on 2022-08-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0003_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='tasks',
            field=models.ManyToManyField(blank=True, related_name='managers', to='client_API.Task', verbose_name='Задание Менеджера'),
        ),
    ]
