# Generated by Django 3.2.9 on 2022-08-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0006_auto_20220829_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='manager',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Created'), ('2', 'In Progress'), ('3', 'Completed')], default='1', max_length=2),
        ),
    ]
