# Generated by Django 3.2.10 on 2022-09-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0007_auto_20220830_1315'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='name_task',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('1', 'Created'), ('2', 'In Progress'), ('3', 'Completed')], default='1', max_length=30),
        ),
    ]
