# Generated by Django 3.2.10 on 2022-11-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_API', '0009_auto_20221112_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='username',
            field=models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Псевдоним'),
        ),
    ]
